architecture:
  arch: "UnetPlusPlus"
  encoder_name: "resnet18"
  encoder_weights: null
  in_channels: 3
  classes: 1
  activation: "identity"


optimizer:
  lr: 0.0005

valid_batch_size: 64
test_batch_size: 64
train_batch_size: 64

early_stopping:
  monitor: "synthetic_valid/correctly_decoded"
  mode: "max"
  min_delta: 0.002
  patience: 5 

trainer:
  accumulate_grad_batches: 1
  max_steps: -1
  max_epochs: -1
  val_check_interval: 200
  log_every_n_steps: 100
  gradient_clip_val: 0.5
  precision: "16-mixed"
