valid_size: 500
test_size: 500
valid_seed: 0
test_seed: 1
valid_batch_size: 64
test_batch_size: 64
train_batch_size: 64

architecture:
  encoder_name: "mobilenet_v2"
  encoder_depth: 3
  encoder_weights: null
  decoder_channels: [10, 10, 10]
  in_channels: 1
  activation: "identity"


optimizer:
  lr: 0.001

trainer:
  max_steps: 5000
  val_check_interval: 50
  log_every_n_steps: 25
